### ISSUE TITLE
[BUG] Telemetry test suit fails due to a malformed packet

### ISSUE THREAD

**Issue by lucasgrelaud** [svpcom/wifibroadcast#113]
**Describe the bug**
The telemetry test suit fails on WFB due to a malformed packet in the *"test_proxy"* test case.

Two issues seems to be at the root of this bug : 
- The packets sent by the test case is badly handled by the [UDPProxyProtocol.write()](https://github.com/svpcom/wifibroadcast/blob/c7ea0a5ddb360cfd6243d5af14fc8a856271fd1d/telemetry/proxy.py#L87) function : 
  the function  expects to unpack a bytes-like object form the the packet array to get the mavlink version, but it gets an array of integer instead => **throws a TypeError**.
- The [Echo.datagramReceived()](https://github.com/svpcom/wifibroadcast/blob/c7ea0a5ddb360cfd6243d5af14fc8a856271fd1d/telemetry/tests/test_proxy.py#L26) function echoes the data it received as a string instead of a bytes-like object.

**To Reproduce**
1. Clone the last version of WFB (at this time : svpcom/wifibroadcast@c7ea0a5)
2. Install all the C/C++ dependencies & Python3 dependencies
3. Build the binaries : `make all_bin`
4. Execute the telemetry test suit : `make test`
 
**Expected behavior**
- [UDPProxyProtocol.write()](https://github.com/svpcom/wifibroadcast/blob/c7ea0a5ddb360cfd6243d5af14fc8a856271fd1d/telemetry/proxy.py#L87) function should store the __"msg"__ data as an array of bytes

**Screenshots**
```bash
2021-02-24 14:56:45+0100 [-] Log opened.
2021-02-24 14:56:45+0100 [-] --> telemetry.tests.test_proxy.UDPProxyTestCase.test_proxy <--
2021-02-24 14:56:45+0100 [-] UDPProxyProtocol starting on 14551
2021-02-24 14:56:45+0100 [-] UDPProxyProtocol starting on 43907
2021-02-24 14:56:45+0100 [-] SendPacket starting on 9999
2021-02-24 14:56:45+0100 [-] Starting protocol <telemetry.tests.test_proxy.SendPacket object at 0x7f41996dd1c0>
2021-02-24 14:56:45+0100 [-] send 10 of b'test' to ('127.0.0.1', 14551)
2021-02-24 14:56:45+0100 [-] Echo starting on 14553
2021-02-24 14:56:45+0100 [-] Starting protocol <telemetry.tests.test_proxy.Echo object at 0x7f41996dd220>
2021-02-24 14:56:46+0100 [Echo (UDP)] got 'testtesttesttesttesttesttesttesttesttest' from ('127.0.0.1', 43907)
2021-02-24 14:56:46+0100 [UDPProxyProtocol (UDP)] msg data (raw) : 116
2021-02-24 14:56:46+0100 [UDPProxyProtocol (UDP)] msg data (char) : t
2021-02-24 14:56:46+0100 [UDPProxyProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib64/python3.9/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/lib64/python3.9/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib64/python3.9/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	  File "/usr/lib64/python3.9/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	--- <exception caught here> ---
	  File "/usr/lib64/python3.9/site-packages/twisted/internet/udp.py", line 249, in doRead
	    self.protocol.datagramReceived(data, addr)
	  File "/home/lucasgrelaud/Dev/UAV/wifibroadcast/telemetry/proxy.py", line 125, in datagramReceived
	    return self._send_to_peer(data)
	  File "/home/lucasgrelaud/Dev/UAV/wifibroadcast/telemetry/proxy.py", line 115, in _send_to_peer
	    self.peer.write(data)
	  File "/home/lucasgrelaud/Dev/UAV/wifibroadcast/telemetry/proxy.py", line 87, in write
	    version = struct.unpack('B', msg[i])[0]
	builtins.TypeError: a bytes-like object is required, not 'int'
	
2021-02-24 14:58:45+0100 [-] Main loop terminated.
2021-02-24 14:58:45+0100 [-] (UDP Port 14551 Closed)
2021-02-24 14:58:45+0100 [-] (UDP Port 43907 Closed)
2021-02-24 14:58:45+0100 [-] --> telemetry.tests.test_proxy.UDPProxyTestCase.test_rssi_injection <--
2021-02-24 14:58:45+0100 [-] UDPProxyProtocol starting on 14551
2021-02-24 14:58:45+0100 [-] UDPProxyProtocol starting on 56163
2021-02-24 14:58:45+0100 [-] (UDP Port 14551 Closed)
2021-02-24 14:58:45+0100 [-] (UDP Port 56163 Closed)
2021-02-24 14:58:45+0100 [-] --> telemetry.tests.test_tuntap.TUNTAPTestCase.test_tuntap <--
2021-02-24 14:58:45+0100 [-] (UDP Port 14553 Closed)
2021-02-24 14:58:45+0100 [-] Stopping protocol <telemetry.tests.test_proxy.Echo object at 0x7f41996dd220>
2021-02-24 14:58:45+0100 [-] (UDP Port 9999 Closed)
2021-02-24 14:58:45+0100 [-] Stopping protocol <telemetry.tests.test_proxy.SendPacket object at 0x7f41996dd1c0>
2021-02-24 14:58:46+0100 [-] Main loop terminated.
```

**Your setup (please complete the following information):**
 - OS Fedora 33 Workstation with Python3.9
 - Hardware : MS Surface Pro 5 (2017)
 - WiFi cards : N.A. (virbr0 & virbr0-nic for the test suit)
 - WiFi drivers : N.A.

**Additional context**

**Confirm you read**
- [x]  https://github.com/svpcom/wifibroadcast/blob/master/README.md
- [x]  https://github.com/svpcom/wifibroadcast/wiki/Setup-HOWTO

**Comment by lucasgrelaud** [comment]
Hi!
Thank you for your work resolving this issue!
I'll close it :D
