### ISSUE TITLE
Config Parse Error after adding UDP Endpoint

### ISSUE THREAD

**Issue by NickNothom** [svpcom/wifibroadcast#45]
Fresh build and install, on two Raspberry Pi 3Bs. 

I get this error after adding the UdpEndpoint to the config file:

```
pi@sparky-gcs:~ $ wfb-cli
Config parse error: [UdpEndpoint wifibroadcast] mode = Normal
Traceback (most recent call last):
  File "/usr/bin/wfb-cli", line 11, in <module>
    load_entry_point('wifibroadcast==19.12.4.85045', 'console_scripts', 'wfb-cli')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/telemetry/cli.py", line 40, in <module>
    from telemetry.common import abort_on_crash, exit_status
  File "/usr/lib/python2.7/dist-packages/telemetry/common.py", line 33, in <module>
    from telemetry.conf import settings
  File "/usr/lib/python2.7/dist-packages/telemetry/conf/__init__.py", line 25, in <module>
    settings, cfg_files = _parse_config()
  File "/usr/lib/python2.7/dist-packages/telemetry/conf/__init__.py", line 22, in _parse_config
    return config_parser.parse_config(os.path.join(os.getcwd(), os.path.dirname(__file__)), telemetry_cfg or _cfg_files)
  File "/usr/lib/python2.7/dist-packages/telemetry/config_parser.py", line 106, in parse_config
    raise ConfigError('Parse error: %s' % (err,))
telemetry.config_parser.ConfigError: Parse error: [UdpEndpoint wifibroadcast] mode = Normal

```

Here's my /etc/wifibroadcast.cfg:

```
[common]
wifi_channel = 161     # 161 -- radio channel @5825 MHz, range: 5815–5835 MHz, width 20MHz
                       # 1 -- radio channel @2412 Mhz, 
                       # see https://en.wikipedia.org/wiki/List_of_WLAN_channels for reference
wifi_region = 'US'     # Your country for CRDA (use BO or GY if you want max tx power)  

[gs_mavlink]
peer = 'connect://127.0.0.1:14550'  # outgoing connection
# peer = 'listen://0.0.0.0:14550'   # incoming connection

[gs_video]
peer = 'connect://127.0.0.1:5600'  # outgoing connection for
                                   # video sink (QGroundControl on GS)


[UdpEndpoint wifibroadcast]
Mode = Normal
Address = 127.0.0.1
Port = 14550

```

Any ideas why I'm getting this? I followed the instructions exactly.

Thanks for reading!

**Comment by svpcom** [comment]
Hi,
What is `[UdpEndpoint wifibroadcast]` section?
Known default values for wifibroadcast are:
``` .ini
[path]
conf_dir = '/etc'
bin_dir = '/usr/bin'
tmp_dir = '/tmp'


[common]
debug = False
version = '0.0.1.trunk'
commit = None

radio_mtu = 1446          # MAX_PAYLOAD_SIZE, don't change if doubt
mavlink_agg_timeout = 0.1 # aggragate mavlink packets if less than radio_mtu but no longer than 100ms
tx_sel_delta = 3          # hysteresis for antenna selection, [dB]
wifi_channel = 165        # radio channel @5825 MHz, range: 5815-5835 MHz, width 20MHz
wifi_region = 'BO'        # Set CRDA region
wifi_txpower = None       # Some cards don't support tx power settings
#wifi_txpower = 58        # for 8812au

[gs_mavlink]
keypair = 'gs.key' # keypair generated by wfb-keygen
stats_port = 8001  # used by wfb-cli
stream_tx = 1      # radio port for mavlink tx
stream_rx = 2      # radio port for mavlink rx
fec_k = 1          # FEC K
fec_n = 2          # FEC N
port_rx = 14600    # udp port for internal use
port_tx = 14601    # udp port range (from port_tx to port_tx + number of wlans) for internal use

peer = 'connect://127.0.0.1:14550'  # outgoing connection
# peer = 'listen://0.0.0.0:14550'   # incoming connection

inject_rssi = True # inject RADIO_STATUS packets

# Radio settings for TX and RX
bandwidth = 20     # bandwidth 20 or 40 MHz

# Radiotap flags for TX:
short_gi = False   # use short GI or not
stbc = 1           # stbc streams: 1, 2, 3 or 0 if unused
ldpc = 0           # use LDPC FEC. Currently available only for 8812au and must be supported both on TX and RX.
mcs_index = 1      # mcs index


[gs_video]
keypair = 'gs.key' # keypair generated by wfb-keygen
stats_port = 8002  # used by wfb-cli
stream = 3         # radio port for video stream
fec_k = 8          # FEC K
fec_n = 12         # FEC N
peer = 'connect://127.0.0.1:5600'  # outgoing connection for video sink (GS)

# Radio settings for RX
bandwidth = 20     # bandwidth 20 or 40 MHz


[drone_mavlink]
keypair = 'drone.key'
stats_port = None
stream_tx = 2
stream_rx = 1
port_rx = 14700
port_tx = 14701
fec_k = 1          # FEC K
fec_n = 2          # FEC N

peer = 'listen://0.0.0.0:14560'   # incoming connection
#peer = 'connect://127.0.0.1:14560'  # outgoing connection

inject_rssi = True # inject RADIO_STATUS packets

# Radio settings for TX and RX
bandwidth = 20     # bandwidth 20 or 40 MHz

# Radiotap flags for TX:
short_gi = False   # use short GI or not
stbc = 1           # stbc streams: 1, 2, 3 or 0 if unused
ldpc = 0           # use LDPC FEC. Currently available only for 8812au and must be supported both on TX and RX.
mcs_index = 1      # mcs index


[drone_video]
keypair = 'drone.key'
stats_port = None
stream = 3
fec_k = 8          # FEC K
fec_n = 12         # FEC N
peer = 'listen://0.0.0.0:5602'  # listen for video stream (drone)

# Radio settings for TX and RX
bandwidth = 20     # bandwidth 20 or 40 MHz

# Radiotap flags for TX:
short_gi = False   # use short GI or not
stbc = 1           # stbc streams: 1, 2, 3 or 0 if unused
ldpc = 0           # use LDPC FEC. Currently available only for 8812au and must be supported both on TX and RX.
mcs_index = 1      # mcs index


[gs_tunnel]
keypair = 'gs.key' # keypair generated by wfb-keygen
stats_port = 8003  # used by wfb-cli
stream_tx = 4      # radio port for tunnel tx
stream_rx = 5      # radio port for tunnel rx
port_rx = 14800    # udp port for internal use
port_tx = 14801    # udp port range (from port_tx to port_tx + number of wlans) for internal use
fec_k = 1          # FEC K
fec_n = 2          # FEC N

ifname = 'gs-wfb'
ifaddr = '10.5.0.1/24'

# Radio settings for TX and RX
bandwidth = 20     # bandwidth 20 or 40 MHz

# Radiotap flags for TX:
short_gi = False   # use short GI or not
stbc = 1           # stbc streams: 1, 2, 3 or 0 if unused
ldpc = 0           # use LDPC FEC. Currently available only for 8812au and must be supported both on TX and RX.
mcs_index = 1      # mcs index

[drone_tunnel]
keypair = 'drone.key'
stats_port = None
stream_tx = 5
stream_rx = 4
port_rx = 14900
port_tx = 14901
fec_k = 1          # FEC K
fec_n = 2          # FEC N

ifname = 'drone-wfb'
ifaddr = '10.5.0.2/24'

# Radio settings for TX and RX
bandwidth = 20     # bandwidth 20 or 40 MHz

# Radiotap flags for TX:
short_gi = False   # use short GI or not
stbc = 1           # stbc streams: 1, 2, 3 or 0 if unused
ldpc = 0           # use LDPC FEC. Currently available only for 8812au and must be supported both on TX and RX.
mcs_index = 1      # mcs index

```
