### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by Abu-Abdullah** [svpcom/wifibroadcast#68]
Hi,

I'm facing the below issue while compiling it in Pi3 lite

```
pi@raspberrypi:~/wifibroadcast $ make
g++  -Wall -O2 -DWFB_VERSION='"20.12.8.43634-8d2d97de"' -std=gnu++11 -c -o src/rx.o src/rx.cpp
cc  -Wall -O2 -DWFB_VERSION='"20.12.8.43634-8d2d97de"' -std=gnu99 -c -o src/radiotap.o src/radiotap.c
cc  -Wall -O2 -DWFB_VERSION='"20.12.8.43634-8d2d97de"' -std=gnu99 -c -o src/fec.o src/fec.c
g++  -Wall -O2 -DWFB_VERSION='"20.12.8.43634-8d2d97de"' -std=gnu++11 -c -o src/wifibroadcast.o src/wifibroadcast.cpp
g++ -o wfb_rx src/rx.o src/radiotap.o src/fec.o src/wifibroadcast.o  -lrt -lpcap -lsodium
g++  -Wall -O2 -DWFB_VERSION='"20.12.8.43634-8d2d97de"' -std=gnu++11 -c -o src/tx.o src/tx.cpp
g++ -o wfb_tx src/tx.o src/fec.o src/wifibroadcast.o  -lrt -lpcap -lsodium
cc  -Wall -O2 -DWFB_VERSION='"20.12.8.43634-8d2d97de"' -std=gnu99 -c -o src/keygen.o src/keygen.c
cc -o wfb_keygen src/keygen.o  -lrt -lpcap -lsodium
PYTHONPATH=`pwd` trial telemetry.tests
telemetry.tests.test_proxy
  UDPProxyTestCase
    test_proxy ...                                                         [OK]
    test_rssi_injection ...                                                [OK]
telemetry
  tests
    test_tuntap ...                                                     [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/trial/runner.py", line 531, in loadPackage
    module = modinfo.load()
  File "/usr/lib/python2.7/dist-packages/twisted/python/modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python2.7/dist-packages/twisted/python/reflect.py", line 255, in _importAndCheckStack
    reraise(excValue, excTraceback)
  File "/home/pi/wifibroadcast/telemetry/tests/test_tuntap.py", line 17, in <module>
    from telemetry.tuntap import TUNTAPTransport, TUNTAPProtocol
  File "/home/pi/wifibroadcast/telemetry/tuntap.py", line 41, in <module>
    from pyroute2 import IPRoute
exceptions.ImportError: No module named pyroute2

telemetry.tests.test_tuntap
-------------------------------------------------------------------------------
Ran 3 tests in 1.153s

FAILED (errors=1, successes=2)
make: *** [Makefile:43: test] Error 1
```

**Comment by Abu-Abdullah** [comment]
sorry, i just see the dependency list in stdeb.cfg
i would suggest to put it in README.md
